const whatsappNumber="595973227879";
const categories=[["Tractores a construcción","cat-construction.webp"],["Automodelos","cat-automodel.webp"],["Tractores agrícolas","cat-agriculture.webp"],["Nautimodelismo","cat-nautical.webp"],["Electrónica","cat-electronics.webp"],["Games","cat-games.webp"],["Speakers y radios","cat-speakers.webp"],["Airsoft infantil","cat-airsoft.webp"],["Juguetes variados","cat-toys.webp"],["Reflectores","cat-lights.webp"],["Miniaturas de colección","cat-miniatures.webp"],["Otros","cat-other.webp"]];
const products=[
  {id:"bitonera-engineering",name:"Bitonera Engineering 20-2",price:"Gs. 250.000",available:true,image:"product-bitonera-engineering.webp",description:"Control 2.4G, batería recargable, sonido, luz y giro de 360°. Medidas aproximadas: 45 × 22 × 13 cm."},
  {id:"tumba-3426",name:"Tumba BC-3426",price:"Gs. 200.000",available:true,image:"product-tumba-3426.webp",description:"Camión de construcción a control remoto. Consultá funciones, escala y colores disponibles."},
  {id:"excavador-xf",name:"Excavador XF Model",price:"Gs. 150.000",available:true,image:"product-excavador-xf.webp",description:"Excavadora a control remoto para sumar acción y realismo a cada juego."},
  {id:"tumba-1041",name:"Tumba BC-1041",price:"Gs. 200.000",available:true,image:"product-tumba-1041.webp",description:"Vehículo de obra a control remoto. Consultá características y disponibilidad actual."},
  {id:"huina-1552",name:"Tractor Huina 1552",price:"No disponible",available:false,image:"product-huina-1552.webp",description:"Modelo Huina de construcción a control remoto. Actualmente sin stock; escribinos para conocer alternativas."},
  {id:"excavadora-r396",name:"Tractor Excavadora R396",price:"No disponible",available:false,image:"product-excavadora-r396.webp",description:"Tractor excavadora a control remoto. Actualmente sin stock; consultá próximos ingresos."},
  {id:"mx-6811l",name:"Tractor excavadora MX 6811L",price:"Gs. 250.000",available:true,image:"product-mx-6811l.webp",description:"Excavadora a control remoto con estética de maquinaria real. Consultá funciones y medidas."},
  {id:"yigong-1037",name:"Tractor Yigong BC-1037",price:"Gs. 250.000",available:true,image:"product-yigong-1037.webp",description:"Tractor Yigong a control remoto, ideal para amantes de la maquinaria de construcción."},
  {id:"track-1039",name:"Tractor Track Type BC-1039",price:"Gs. 200.000",available:true,image:"product-track-1039.webp",description:"Vehículo de oruga a control remoto. Consultá colores, alcance y contenido del paquete."},
  {id:"bitonera-huina",name:"Bitonera Huina 1574",price:"Gs. 1.200.000",available:true,image:"product-bitonera-huina.webp",description:"Modelo premium Huina a control remoto con detalles realistas y funciones avanzadas."},
  {id:"camion-huina",name:"Camión Huina 1573",price:"Gs. 1.200.000",available:true,image:"product-camion-huina.webp",description:"Camión Huina premium a control remoto. Consultá demostración en video y disponibilidad."},
  {id:"empilladeira-huina",name:"Empilladeira Huina 1577",price:"Gs. 1.200.000",available:true,image:"product-empilladeira-huina.webp",description:"Montacargas Huina premium a control remoto con terminación detallada y funciones realistas."}
];
const categoryGrid=document.getElementById("category-grid"),productGrid=document.getElementById("product-grid"),search=document.getElementById("search"),resultCount=document.getElementById("result-count"),emptyState=document.getElementById("empty-state"),dialog=document.getElementById("product-dialog");
let activeFilter="all",selectedCategory="Tractores a construcción";
categoryGrid.innerHTML=categories.map(([name,image],index)=>`<button class="category-card" type="button" data-category="${name}"><figure><img src="assets/catalog/${image}" alt="${name}" loading="lazy"></figure><div><h3>${name}</h3><span>${String(index+1).padStart(2,"0")} ↗</span></div></button>`).join("");
function filteredProducts(){if(selectedCategory!=="Tractores a construcción")return[];const term=search.value.trim().toLocaleLowerCase("es");return products.filter(product=>product.name.toLocaleLowerCase("es").includes(term)&&(activeFilter==="all"||(activeFilter==="available"&&product.available)||(activeFilter==="unavailable"&&!product.available)))}
function renderProducts(){const visible=filteredProducts();productGrid.innerHTML=visible.map(product=>`<button class="product-card" type="button" data-product-id="${product.id}" aria-label="Ver ${product.name}"><figure><img src="assets/catalog/${product.image}" alt="${product.name}" loading="lazy"><span class="availability ${product.available?"":"out"}">${product.available?"Disponible":"Agotado"}</span></figure><div class="product-copy"><p class="product-category">Tractores RC</p><h3>${product.name}</h3><div class="product-price"><strong>${product.price}</strong><span>↗</span></div></div></button>`).join("");resultCount.textContent=`${visible.length} ${visible.length===1?"producto":"productos"}`;emptyState.hidden=visible.length!==0;document.getElementById("empty-copy").textContent=selectedCategory==="Tractores a construcción"?"No encontramos ese producto.":`Consultá los productos disponibles en ${selectedCategory}.`;document.getElementById("empty-link").href=`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(`Hola, quiero ver los productos de ${selectedCategory}.`)}`}
function openProduct(id){const product=products.find(item=>item.id===id);if(!product)return;const image=document.getElementById("dialog-image");image.src=`assets/catalog/${product.image}`;image.alt=product.name;document.getElementById("dialog-title").textContent=product.name;document.getElementById("dialog-description").textContent=product.description;document.getElementById("dialog-status").textContent=product.available?"Disponible ahora":"Consultá próximos ingresos";document.getElementById("dialog-price").textContent=product.price;document.getElementById("dialog-whatsapp").href=`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(`Hola, quiero consultar por ${product.name} (${product.price}). ¿Sigue disponible?`)}`;dialog.showModal()}
renderProducts();
search.addEventListener("input",()=>{selectedCategory="Tractores a construcción";document.getElementById("catalog-title").textContent="Tractores a control remoto.";renderProducts()});
document.querySelectorAll("[data-filter]").forEach(button=>button.addEventListener("click",()=>{activeFilter=button.dataset.filter;document.querySelectorAll("[data-filter]").forEach(item=>item.classList.toggle("active",item===button));renderProducts()}));
productGrid.addEventListener("click",event=>{const card=event.target.closest("[data-product-id]");if(card)openProduct(card.dataset.productId)});
const featured=document.querySelector(".hero-product");featured.addEventListener("click",()=>openProduct(featured.dataset.productId));featured.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();openProduct(featured.dataset.productId)}});
categoryGrid.addEventListener("click",event=>{const card=event.target.closest("[data-category]");if(!card)return;selectedCategory=card.dataset.category;search.value="";document.getElementById("catalog-title").textContent=`${selectedCategory}.`;document.getElementById("productos").scrollIntoView({behavior:"smooth"});renderProducts()});
document.querySelector(".dialog-close").addEventListener("click",()=>dialog.close());dialog.addEventListener("click",event=>{if(event.target===dialog)dialog.close()});document.getElementById("year").textContent=new Date().getFullYear();
