const categories=[
  {id:"electronics",name:"Electrónica",image:"electronics.webp",description:"Audio, conectividad y tecnología para todos los días."},
  {id:"toys",name:"Juguetes",image:"toys.webp",description:"Opciones para regalar, crear, jugar y sorprender."},
  {id:"accessories",name:"Accesorios",image:"accessories.webp",description:"Complementos tecnológicos y artículos prácticos para todos los días."}
];
const categoryGrid=document.getElementById("category-grid"),productGrid=document.getElementById("product-grid"),search=document.getElementById("search"),resultCount=document.getElementById("result-count"),emptyState=document.getElementById("empty-state"),dialog=document.getElementById("product-dialog");
let activeFilter="all";
categoryGrid.innerHTML=categories.map((item,index)=>`<button class="category-card" type="button" data-product-id="${item.id}"><figure><img src="assets/${item.image}" alt="${item.name}" loading="lazy"></figure><div><h3>${item.name}</h3><span>${String(index+1).padStart(2,"0")} ↗</span></div></button>`).join("");
function filteredItems(){const term=search.value.trim().toLocaleLowerCase("es");return categories.filter(item=>(activeFilter==="all"||item.id===activeFilter)&&(item.name.toLocaleLowerCase("es").includes(term)||item.description.toLocaleLowerCase("es").includes(term)))}
function renderProducts(){const visible=filteredItems();productGrid.innerHTML=visible.map(item=>`<button class="product-card" type="button" data-product-id="${item.id}" aria-label="Ver ${item.name}"><figure><img src="assets/${item.image}" alt="${item.name}" loading="lazy"><span class="availability">Consultar modelos</span></figure><div class="product-copy"><p class="product-category">Colección</p><h3>${item.name}</h3><div class="product-price"><strong>Ver opciones</strong><span>↗</span></div></div></button>`).join("");resultCount.textContent=`${visible.length} ${visible.length===1?"categoría":"categorías"}`;emptyState.hidden=visible.length!==0}
function openItem(id){const item=categories.find(entry=>entry.id===id);if(!item)return;const image=document.getElementById("dialog-image");image.src=`assets/${item.image}`;image.alt=item.name;document.getElementById("dialog-title").textContent=item.name;document.getElementById("dialog-description").textContent=item.description;document.getElementById("dialog-status").textContent="Modelos y disponibilidad";document.getElementById("dialog-price").textContent="A confirmar";document.getElementById("dialog-inquiry").dataset.category=item.name;dialog.showModal()}
renderProducts();
search.addEventListener("input",renderProducts);
document.querySelectorAll("[data-filter]").forEach(button=>button.addEventListener("click",()=>{activeFilter=button.dataset.filter;document.querySelectorAll("[data-filter]").forEach(item=>item.classList.toggle("active",item===button));renderProducts()}));
document.addEventListener("click",event=>{const card=event.target.closest("[data-product-id]");if(card)openItem(card.dataset.productId)});
const featured=document.querySelector(".hero-product");featured.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();openItem(featured.dataset.productId)}});
document.querySelector(".dialog-close").addEventListener("click",()=>dialog.close());dialog.addEventListener("click",event=>{if(event.target===dialog)dialog.close()});
document.getElementById("dialog-inquiry").addEventListener("click",event=>{const category=event.currentTarget.dataset.category||"";document.getElementById("inquiry-product").value=category;dialog.close()});
document.getElementById("quick-inquiry").addEventListener("submit",async event=>{event.preventDefault();const name=document.getElementById("inquiry-name").value.trim(),product=document.getElementById("inquiry-product").value.trim(),text=`Hola, soy ${name}. Quiero consultar por ${product} en Lojas Americanas Salto del Guairá.`;if(navigator.share){await navigator.share({title:"Consulta de catálogo",text})}else{await navigator.clipboard.writeText(text);document.getElementById("contact-note").textContent="Consulta copiada. Pegala en tu aplicación de mensajes."}});
document.getElementById("year").textContent=new Date().getFullYear();
